### ISSUE TITLE
Asking about the max_time 

### ISSUE THREAD

**Issue by quanpn90** [harvardnlp/sent-conv-torch#12]
Hi authors,

Could I ask for an explanation for the part 

max_time = nn.Max(3)(cudnn.ReLU()(conv_layer)) 

Theoretically, Is it different than using a temporal maxpooling on conv_layer ? I am quite confused at this part, because when I tried to use temporal maxpooling on the whole output sequence, it gave me different result. 

Thank you very much,

**Comment by jeffreyling** [comment]
Hi, this part combines the nonlinearity ReLU with temporal maxpooling. Does this answer your question?

**Comment by quanpn90** [comment]
Hi, thanks.

I see that you apply the convolution, then reshape it to opt.num_feat_maps, opt.max_sent-kernels[i]+1, then take the max over the opt.max_sent-kernels[i]+1 dimension. 

I wonder if the following operations are mathematically the same. 

- do convolution 
conv_output = conv(nn.Reshape(1, opt.max_sent, opt.vec_size, true)(lookup)))

-then do activation + temporal max pooling
output = nn.TemporalMaxPooling(cudnn.ReLU()(conv_output)) 

That's what I intended to ask. Sorry for the confusion.

**Comment by jeffreyling** [comment]
I looked into TemporalMaxPooling (this didn't exist at the time code was written, neither was nn.Squeeze). I think the following series of commands are equivalent:

* do convolution:
conv_output = nn.Reshape(...)(conv(nn.Reshape(1, opt.max_sent, opt.vec_size, true)(lookup)))

This can also be implemented more simply by replacing the outer Reshape with Squeeze.

followed by either
* max:
output = nn.Max(3)(cudnn.ReLU()(conv_output))

* temporal maxpooling:
output = nn.Squeeze()(nn.TemporalMaxPooling(opt.max_sent - kernels[i] + 1)(nn.Transpose({2,3})(cudnn.ReLU()(conv_output))))


since TemporalMaxPooling takes an argument of the size of the pool.

Let me know if this makes sense.

**Comment by quanpn90** [comment]
Thanks so much Jeffreyling,

Now I see that the nn.Transpose is what that makes the difference in my original question. I feel pretty relieved now about that. However, I am not sure that I understand the role of Transpose, could you please explain that to me ?

Best regards, and happy Easter !!!

**Comment by jeffreyling** [comment]
It's needed because nn.TemporalMaxPooling does pooling over the first dimension (in batch mode, that's dimension 2). We have to swap dimensions 2 and 3 of conv_output since the time dimension is 3. In this case, Max would probably be the simpler operation...

Hope that helps!
